CREATE TABLE Alunos (
ID INT PRIMARY KEY NOT NULL,
NOME VARCHAR(50),
CPF VARCHAR(15),
Dt_Nasci DATE,
Tel CHAR(15)
);

CREATE TABLE Instrutores (
ID INT PRIMARY KEY NOT NULL,
NOME VARCHAR(50),
Email VARCHAR(50),
dt_Nasci DATE,
Certificados VARCHAR(255),
Valor_Hora INT
);

CREATE TABLE Cursos (
ID INT PRIMARY KEY NOT NULL,
NOME VARCHAR(50),
Carga_hr SMALLINT,
preco DOUBLE PRECISION
);

CREATE TABLE Matriculas (
ID INT PRIMARY KEY NOT NULL,
ID_Turma INT,
ID_Alunos INT,
dt_Matricula DATE
);

CREATE TABLE turmas (
ID INT PRIMARY KEY NOT NULL,
ID_Instrutor INT,
ID_Curso INT,
Dt_Inicio DATE,
Dt_Fim DATE,
Carga_Hr SMALLINT
);

ALTER TABLE turmas
ADD CONSTRAINT Turma_FKIntrustor FOREIGN KEY (ID_Instrutor) REFERENCES instrutores (ID);
ALTER TABLE turmas
ADD CONSTRAINT Turma_FKCurso FOREIGN KEY (ID_Curso) REFERENCES cursos (ID);

ALTER TABLE Matriculas
ADD CONSTRAINT Matriculas_FKTurma FOREIGN KEY (ID_Turma) REFERENCES turmas (ID);
ALTER TABLE Matriculas
ADD CONSTRAINT Matriculas_FKAlunos FOREIGN KEY (ID_Alunos) REFERENCES alunos (ID);
